version: '3'
services:
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      nightout:
        aliases:
            - mariadb
        ipv4_address: 172.0.0.4

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test_pass # TODO: Change this
      MYSQL_DATABASE: hackathon
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    networks:
      nightout:
        aliases:
            - mariadb
        ipv4_address: 172.0.0.3

  nightout:
    image: nightout
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nightout:/opt/nightout
    environment:
      - DJANGO_SETTINGS_MODULE=nightout.production
      - SECRET_KEY=z3l6=^qdf@m*%%hyc**hzw_^^69%**5sd4ae7#shfjh(=jd3a(
    networks:
      nightout:
        aliases:
            - nginx
        ipv4_address: 172.0.0.2

networks:
  nightout:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24
