# Generated by Django 2.0.4 on 2018-04-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=140)),
                ('time', models.DateTimeField(max_length=30)),
                ('date', models.DateTimeField(max_length=30)),
                ('local', models.CharField(max_length=30)),
                ('private', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('oauthkey', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='friends',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='mainsite.Users'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='mainsite.Users'),
        ),
        migrations.AddField(
            model_name='attending',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Eventos'),
        ),
        migrations.AddField(
            model_name='attending',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Users'),
        ),
    ]
