# Generated by Django 2.0.4 on 2018-04-14 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=140)),
                ('image', models.FileField(upload_to='upload/')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, max_length=30)),
                ('local', models.CharField(max_length=30)),
                ('private', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('events', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('oauthkey', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='attending',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Events'),
        ),
    ]
