# Generated by Django 2.0.4 on 2018-04-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='local',
            field=models.CharField(max_length=1000),
        ),
    ]
