# Generated by Django 2.0.4 on 2018-04-14 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='date',
            field=models.DateTimeField(default=datetime.time(0, 0), max_length=30),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='time',
            field=models.DateTimeField(default=datetime.time(0, 0), max_length=30),
        ),
    ]
