# Generated by Django 2.0.4 on 2018-04-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.FileField(blank=True, upload_to='uploaded/'),
        ),
        migrations.AddField(
            model_name='night',
            name='image',
            field=models.FileField(blank=True, upload_to='uploaded/'),
        ),
    ]
