# Generated by Django 2.0.4 on 2018-04-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attending',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='events',
            name='users',
            field=models.ManyToManyField(to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='mainsite.User'),
        ),
        migrations.AlterField(
            model_name='attending',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Events'),
        ),
    ]
