# Generated by Django 2.0.4 on 2018-04-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='descr',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='eventos',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventos',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
