# Generated by Django 2.0.4 on 2018-04-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180414_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descr',
            field=models.CharField(max_length=140),
        ),
    ]
