# Generated by Django 2.0.4 on 2018-04-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180414_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
