# Generated by Django 2.0.4 on 2018-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180415_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.FileField(upload_to='uploaded/'),
        ),
    ]
