# Generated by Django 2.0.4 on 2018-04-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20180414_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='date',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='time',
            field=models.DateTimeField(max_length=30),
        ),
    ]
