# Generated by Django 2.0.4 on 2018-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180414_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='users',
            field=models.ManyToManyField(related_name='events', to='mainsite.User'),
        ),
    ]
