# Generated by Django 2.0.4 on 2018-04-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_events_eventname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='eventname',
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default='Teste', max_length=30),
            preserve_default=False,
        ),
    ]
