# Generated by Django 2.0.4 on 2018-04-14 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_events_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='creator',
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=30),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=30),
        ),
    ]
