# Generated by Django 2.0.4 on 2018-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180415_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='night',
            name='image',
            field=models.FileField(upload_to='uploaded/'),
        ),
    ]
