# Generated by Django 2.0.4 on 2018-04-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180414_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='night',
            old_name='events',
            new_name='title',
        ),
    ]
