# Generated by Django 2.0.4 on 2018-04-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180414_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='upload/'),
        ),
    ]
