# Generated by Django 2.0.4 on 2018-04-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180414_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
