# Generated by Django 2.0.4 on 2018-04-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20180414_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='night',
            name='events',
            field=models.ManyToManyField(related_name='events', to='mainsite.Events'),
        ),
    ]
