# Generated by Django 2.0.4 on 2018-04-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_night_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='night',
            name='events',
        ),
        migrations.AddField(
            model_name='night',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mainsite.Events'),
            preserve_default=False,
        ),
    ]
