# Generated by Django 2.0.4 on 2018-04-14 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20180414_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='night',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='night',
            name='users',
        ),
        migrations.AddField(
            model_name='night',
            name='events',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 11, 14, 40, 102458, tzinfo=utc), max_length=30),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 11, 14, 40, 102412, tzinfo=utc), max_length=30),
        ),
    ]
