# Generated by Django 2.0.4 on 2018-04-14 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20180414_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='night',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='night',
            name='users',
        ),
        migrations.AlterField(
            model_name='eventos',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 14, 25, 53, 325753, tzinfo=utc), max_length=30),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 14, 25, 53, 325709, tzinfo=utc), max_length=30),
        ),
        migrations.DeleteModel(
            name='Night',
        ),
    ]
