# Generated by Django 2.0.4 on 2018-04-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_events_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AlterField(
            model_name='attending',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
        migrations.AlterField(
            model_name='events',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='social_django.UserSocialAuth'),
        ),
        migrations.AlterField(
            model_name='events',
            name='users',
            field=models.ManyToManyField(to='social_django.UserSocialAuth'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='social_django.UserSocialAuth'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='social_django.UserSocialAuth'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
