# Generated by Django 2.0.4 on 2018-04-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20180415_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
