# Generated by Django 2.0.4 on 2018-04-14 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20180414_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 13, 30, 45, 66284, tzinfo=utc), max_length=30),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 13, 30, 45, 66228, tzinfo=utc), max_length=30),
        ),
    ]
