# Generated by Django 2.0.4 on 2018-04-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20180414_1504'),
        ('mainsite', '0009_auto_20180414_1330'),
    ]

    operations = [
    ]
