# Generated by Django 2.0.4 on 2018-04-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_night_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='night',
            old_name='group',
            new_name='user',
        ),
    ]
