# Generated by Django 2.0.4 on 2018-04-15 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20180415_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='night',
            name='events',
        ),
        migrations.AddField(
            model_name='night',
            name='events',
            field=models.ManyToManyField(related_name='events', to='mainsite.Events'),
        ),
        migrations.AlterField(
            model_name='night',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
