# Generated by Django 2.0.4 on 2018-04-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_user_picture'),
        ('mainsite', '0011_auto_20180415_0251'),
    ]

    operations = [
    ]
